### ISSUE TITLE
Request Modification for Printing Numbers

### ISSUE THREAD

**Issue by TrekManiac** [jvsrinivasan/Letter-Pattern-using-COBOL#1]
I was able to use this program to help design z/VM logo screens, thanks for the contribution.  Would it be an easy modification to allow for printing numbers in addition to letters?

**Comment by jvsrinivasan** [comment]
It is an easy modification and I'll add the code by end of this week.

**Comment by TrekManiac** [comment]
Thank you!  I'll be on the lookout for the modification.  Great contribution, love it for assisting in logo screen design.
